### PR TITLE
Changes to strategy and ai_lou

### PR DESCRIPTION
**Pull request by orang455**
strategy.js change was needed to support shift power and shift token
changes to ai_lou to implement shape shift and give value to dwelling that will extend network

There are still many improvements and ai left to do.

I will have no Email service from 2015 June 20 to July 7 (Greece/Turkey)

### CODE REVIEW

**Comment by orang455** [comment]
These changes made a substantial difference in performance connectivity and shape shifters ability.
It does not appear that these changes made it to the the web so the testers can access...:

lodev.org/tmai

The date on the public version is still two months ago:...

TM AI: Play TM against AI players.
Programmed by Lode Vandevenne.
AI tweaks by Lou New.
Drawings by Giordano Segatta.
version: v.20150509

The next change from me will be how the order of build proceeds in AI_lou.  Some factions should stop at 6 points and use the 2 red favor.
Also, it is more important to secure space and connectivity for the second town than to complete the first town.
The sanctuary should be reserved for the case of only three spaces, and also be connected for the SH-SA  fire-ice distance bonus.

## Town building should be reserved to get the town round bonus (especially for mermaids water town).

On Sun, 6/21/15, lvandeve notifications@github.com wrote:

 Subject: Re: [tmai] Changes to strategy and ai_lou (#5)
 To: "lvandeve/tmai" tmai@noreply.github.com
 Cc: "orang455" orang455@yahoo.com
 Date: Sunday, June 21, 2015, 1:10 PM

 Merged #5.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by lvandeve** [comment]
Hi,

Done, sorry for the delay. Updated to latest version from github now.

Feel free to remind me sooner next time if I forget.

The menu version didn't match the last update tho, that was on 25 may.

**Comment by orang455** [comment]
Thanks.  The new version checks out correctly.  
Riverwalkers play well even without the Stronghold bridges.

## The Shapeshifters now shift, but improvement needed.

On Thu, 7/9/15, lvandeve notifications@github.com wrote:

 Subject: Re: [tmai] Changes to strategy and ai_lou (#5)
 To: "lvandeve/tmai" tmai@noreply.github.com
 Cc: "orang455" orang455@yahoo.com
 Date: Thursday, July 9, 2015, 1:06 PM

 Hi,

 Done, sorry for the delay. Updated to latest version from
 github now.

 Feel free to remind me sooner next time if I forget.

 The menu version didn't match the last update tho,
 that was on 25 may.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by orang455** [comment]
Greetings:

I have worked on several improvements to TMAI.  Phasing is the biggest change for all factions.
1. Tablets and touch screens:  I got a new IPAD Air2 and tested TMAI on it.  I had several observations:
   Everything that I tied worked like it did on my home PC.
   Even on the larger IPAD screen, several times I had to make the picture bigger so my fingers would activate.  Fingers are not as accurate as a mouse and pointer.  Therefore, I make the following suggestions::
   A. the top line with five items needs larger font and a box around the options.  In particular, the "new" item is small and should be larger in both directions.  It appears close to the top edge and sometimes the touch activated the wrong item.
   B.  The pop-up windows for faction and color should be larger and preferably boxed to give more touch space.
   C.  The player options to go from blank to D, and from D to TP work well by touching the hex.  Theother options needing the screen box are just text and do not take up all the space in the area.  The Cult option should b e bigger, Cult1, Cult2, and Cult3 are less important.  I suppose I would like to see all of the space in the box used more efficiently with larger touch areas.
   D.  I am not a touch screen human factors person and will leave that to you if you wish.
2. Final scoring options:  Too much of the time there are zeros for VP for the SH_SA option.  I have added extensive code to the AI module to make this more effective by accounting for the 18/12/6 points available and properly placing the SA so that it assists in a 3 space town as well as a distance away from the SH.  The current system for SH and SA placement is not effective to collect this bonus.  Additional emphasis was placed on placing the D in outpost locations when the Outpost final scoring occurs.
3. Selection of faction:  One key to successful TM play is to select a faction and potentially a color depending upon the round and bonus tiles selected.  The faction color probabilities have changed accordingly.  Thee is still some chance of poor performance choices, but the likelihood of better factions has increased, depending upon world selection, round/bonus  tile choice, other factions, and number of players.
4.  Icemaidens:  These were being played all wrong.  They now build temples and get the SH to get points for them.
5.  Phasing:  This is the most important change.  Much better scores are achieved when the faction collects the round bonus for the action.  SH/SA should be built when the round tile is available.  TP should be built when the two 3VP round tiles are in the round and it would help if the 3VP TP favor tile was also used.   Town building should be delayed until the round tile for town is available especially for mermaids that can form a water town in any round.  .Town building currently goes to a count of 7 points when stopping at 6 points and then using the 2 Fire favor or waiting for a TP round would be better.  Logic has been added to delay these actions for one/two rounds.  Better players will plan their activities taking the entire round sequence into account including faction selection.
6. Play testing:  Thee were several combinations of actions that led to poor results.  Some minor tuning has been added to avoid these situations.
7. Bridges: not used by Engineers yet, or the SH for Riverwalkers.  Sometimes bridges are used prematurely to make a town.  They can also be used to expand a town to a different color tile on the other side.when shipping not available.

Changes coming soon...

**Pull request merged**
